function [BW,maskedImage] = segmentImage(X)
%segmentImage Segment image using auto-generated code from imageSegmenter app
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the imageSegmenter app. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 09-Dec-2018
%----------------------------------------------------


% Threshold image - global threshold
BW = imbinarize(X);

% Create masked image.
maskedImage = X;
maskedImage(~BW) = 0;
end

